apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name}} 
spec:
  type: {{ .Values.app.service.type }}
  ports:
  - name : {{ .Values.app.service.ports.app.name }}
    port: {{ .Values.app.service.ports.app.port }}
    targetPort: {{ .Values.app.service.ports.app.targetPort }}
    nodePort: {{ .Values.app.service.ports.app.nodePort}}
    protocol: {{ .Values.app.service.ports.app.protocol }}
  selector:
    app: {{ .Values.app.name }}
    
